<?php

/**
 * @file
 * Module file for the Admin Toggle module.
 */

/**
 * Implements hook_menu().
 */
function admin_toggle_menu() {
  $items['admin/config/administration/admin_toggle'] = array(
    'title' => 'Admin Toggle',
    'description' => 'Modify Admin Toggle settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('admin_toggle_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'admin_toggle.admin.inc',
  );

  $items['admin_toggle/toggle'] = array(
    'title' => 'Admin Toggle',
    'page callback' => 'admin_toggle_toggle',
    'access arguments' => array('use admin toggle'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function admin_toggle_init() {
  if (user_access('use admin toggle')) {
    $settings = array(
      'adminToggle' => array(
        'key' => variable_get('admin_toggle_key', '`'),
        'selector' => admin_toggle_get_selector(),
        'default' => admin_toggle_default(),
      ),
    );
    drupal_add_js($settings, 'setting');
    drupal_add_js(drupal_get_path('module', 'admin_toggle') . '/admin_toggle.js');
  }
}

/**
 * Implements hook_permission().
 */
function admin_toggle_permission() {
  return array(
    'use admin toggle' => array(
      'title' => t('Use Admin Toggle'),
      'description' => t('Use Admin Toggle functionality.'),
    ),
    'administer admin toggle' => array(
      'title' => t('Administer Admin Toggle'),
      'description' => t('Modify settings for Admin Toggle.'),
    ),
  );
}

/**
 * Implements hook_preprocess_block().
 */
function admin_toggle_preprocess_block(&$vars) {
  $block = $vars['block'];
  if (
    ($block->module == 'system' && $block->delta == 'management')
    || $block->module == 'devel'
  ) {
    $vars['classes_array'][] = 'admin-toggle';
  }
}

/**
 * Return the jQuery selector for admin elements to toggle.
 */
function admin_toggle_get_selector() {
  // Build an array of selectors.
  $selectors = array(
    variable_get('admin_toggle_custom_selector'),
    '.admin-toggle',
    '.action-links',
  );
  return implode(',', $selectors);
}

/**
 * Menu callback; toggle the user's show/hide preference.
 */
function admin_toggle_toggle() {
  if (isset($_POST['admin_toggle'])) {
    $_SESSION['admin_toggle'] = $_POST['admin_toggle'];
  }
}

/**
 * Get the default toggle state, either by a session variable or an admin
 * preference.
 *
 * @return
 *   Either 0 or 1, where 0 represents admin elements toggled off and 1
 *   represents admin elements toggled on.
 */
function admin_toggle_default() {
  if (isset($_SESSION['admin_toggle'])) {
    return ($_SESSION['admin_toggle']);
  }

  return variable_get('admin_toggle_default', 1);
}
